INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Dmitry', '2004-12-02', 'Trainee', 100000);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Max', '2005-09-26', 'Junior', 100000);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Anastasiia', '2004-11-20', 'Middle', 99000);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Artem', '2005-07-14', 'Trainee', 100);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Alex', '1981-06-12', 'Senior', 50000);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Sofia', '1999-11-28', 'Junior', 6000);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Denis', '1980-09-15', 'Trainee', 4000);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Thomas', '2000-12-12', 'Junior', 8000);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Harry', '1995-03-03', 'Senior', 100000);
INSERT INTO worker (NAME, BIRTHDAY, LEVEL, SALARY) VALUES ('Charlie', '2004-05-22', 'Middle', 33000);

INSERT INTO client (NAME) VALUES ('Henry');
INSERT INTO client (NAME) VALUES ('William');
INSERT INTO client (NAME) VALUES ('Oliver');
INSERT INTO client (NAME) VALUES ('Mary');
INSERT INTO client (NAME) VALUES ('Alexandra');

INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (1, '2023-03-20', '2024-01-01');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (2, '2022-01-01', '2024-01-01');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (3, '2020-05-05', '2025-01-01');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (1, '2021-05-20', '2028-06-21');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (1, '2023-03-26', '2029-09-01');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (4, '2028-09-29', '2030-04-25');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (5, '2014-03-20', '2020-12-01');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (3, '2024-11-20', '2026-07-21');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (4, '2021-03-20', '2027-01-01');
INSERT INTO project (CLIENT_ID, START_DATE, FINISH_DATE) VALUES (1, '2023-03-20', '2024-11-30');

INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (1, 2);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (4, 8);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (4, 5);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (1, 6);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (2, 9);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (4, 4);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (3, 5);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (2, 8);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (3, 1);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (1, 3);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (2, 10);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (3, 10);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (2, 2);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 8);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 9);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (10, 10);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (10, 2);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 1);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (9, 9);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (9, 6);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 6);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (8, 3);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (8, 4);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (7, 2);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (7, 5);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 7);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (6, 3);




